name: My awesome workflow
on: push
jobs:
  build:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
      with:
        MY_NAME: "Tim the great"